# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 214de30a337091968ab66c9f619823400a11cce16688a81fa771047b2cdc175d68e6225fecf66848cc413df1a2cbe2aacda12c5f1aedd07c49566e2c8f9805c7

test:
  secret_key_base: fbda4fb15bd8ffee97059e1cbd8a923d6084e86bd09aca448473d45a05c017bde3d6ac46ae000eaa03a1bb9749ba1bd210c50d113ae88718cf62063b2828f0b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: "rubylaser.org"
  admin_email: "admin@rubylaser.org"
  admin_pass: <%= ENV["ADMIN_PASS"] %>
